name: CI Tests

on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type-check
        run: deno check **/*.ts **/*.tsx

      - name: Cache dependencies
        run: deno cache dev.ts

      - name: Start Fresh server in background
        run: deno task dev &

      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:8000 > /dev/null; do sleep 1; done'
          echo "Server is ready"

      - name: Run E2E tests
        run: deno task test:e2e

      - name: Stop server
        run: pkill -f "deno task dev" || true
